#!/usr/bin/env python
'''
Rename histograms for 8TeV datacards 
Author: T.M.Perry
'''
import ROOT
from ROOT import *

inFilename = raw_input ('Name of File to be Renamed (no .root):\n')


#inFilename = 'Datacard_2j2525_2bt_highestJetPt'
inFile = TFile(inFilename+'.root')

outFile=gROOT.FindObject('Renamed_'+inFilename+'.root')
if outFile : outFile.Close()
outFile = TFile('Renamed_'+inFilename+'.root','RECREATE','renamed histograms')
log = open(inFilename+'.log','a')

# Unshifted
data_obs_INFILE = inFile.Get("dataih")
data_obs = data_obs_INFILE.Clone()
data_obs.SetName("data_obs")

Wbb_INFILE = inFile.Get("wbbihNo")
Wbb = Wbb_INFILE.Clone()
Wbb.SetName("Wbb")
TTbar_INFILE = inFile.Get("ttbihNo")
TTbar = TTbar_INFILE.Clone()
TTbar.SetName("TTbar")
Wcc_INFILE = inFile.Get("wccihNo")
Wcc = Wcc_INFILE.Clone()
Wcc.SetName("Wcc")
T_INFILE = inFile.Get("tihNo")
T = T_INFILE.Clone()
T.SetName("T")
Tbar_INFILE = inFile.Get("tbihNo")
Tbar = Tbar_INFILE.Clone()
Tbar.SetName("Tbar")
tW_INFILE = inFile.Get("t_twihNo")
tW = tW_INFILE.Clone()
tW.SetName("tW")
Drell_INFILE = inFile.Get("zihNo")
Drell = Drell_INFILE.Clone()
Drell.SetName("Drell")
VV_INFILE = inFile.Get("vvihNo")
VV = VV_INFILE.Clone()
VV.SetName("VV")
QCD_INFILE = inFile.Get("qhNo")
QCD = QCD_INFILE.Clone()
QCD.SetName("QCD")

log.write('\n\n')
log.write("data:  "+str(data_obs.Integral())+'\n')
log.write("Wbb:   "+str(Wbb.Integral())     +'\n')
log.write("TTbar: "+str(TTbar.Integral())   +'\n')
log.write("Wcc:   "+str(Wcc.Integral())     +'\n')
log.write("T:     "+str(T.Integral())       +'\n')
log.write("Tbar:  "+str(Tbar.Integral())    +'\n')
log.write("tW:    "+str(tW.Integral())      +'\n')
log.write("Drell: "+str(Drell.Integral())   +'\n')
log.write("VV:    "+str(VV.Integral())      +'\n')
log.write("QCD:   "+str(QCD.Integral())     +'\n')
log.close()

# TTbar Up
Wbb_INFILE_TTUp = inFile.Get("wbbihTup")
Wbb_TTUp = Wbb_INFILE_TTUp.Clone()
Wbb_TTUp.SetName("Wbb_TTUp")
Wcc_INFILE_TTUp = inFile.Get("wccihTup")
Wcc_TTUp = Wcc_INFILE_TTUp.Clone()
Wcc_TTUp.SetName("Wcc_TTUp")
TTbar_INFILE_TTUp = inFile.Get("ttbihTup")
TTbar_TTUp = TTbar_INFILE_TTUp.Clone()
TTbar_TTUp.SetName("TTbar_TTUp")
T_INFILE_TTUp = inFile.Get("tihTup")
T_TTUp = T_INFILE_TTUp.Clone()
T_TTUp.SetName("T_TTUp")
Tbar_INFILE_TTUp = inFile.Get("tbihTup")
Tbar_TTUp = Tbar_INFILE_TTUp.Clone()
Tbar_TTUp.SetName("Tbar_TTUp")
tW_INFILE_TTUp = inFile.Get("t_twihTup")
tW_TTUp = tW_INFILE_TTUp.Clone()
tW_TTUp.SetName("tW_TTUp")
Drell_INFILE_TTUp = inFile.Get("zihTup")
Drell_TTUp = Drell_INFILE_TTUp.Clone()
Drell_TTUp.SetName("Drell_TTUp")
VV_INFILE_TTUp = inFile.Get("vvihTup")
VV_TTUp = VV_INFILE_TTUp.Clone()
VV_TTUp.SetName("VV_TTUp")
#QCD_INFILE_TTUp = inFile.Get("qhTup")
#QCD_TTUp = QCD_INFILE_TTUp.Clone()
#QCD_TTUp.SetName("QCD_TTUp")

# TTbar Down
Wbb_INFILE_TTDown = inFile.Get("wbbihTdn")
Wbb_TTDown = Wbb_INFILE_TTDown.Clone()
Wbb_TTDown.SetName("Wbb_TTDown")
Wcc_INFILE_TTDown = inFile.Get("wccihTdn")
Wcc_TTDown = Wcc_INFILE_TTDown.Clone()
Wcc_TTDown.SetName("Wcc_TTDown")
TTbar_INFILE_TTDown = inFile.Get("ttbihTdn")
TTbar_TTDown = TTbar_INFILE_TTDown.Clone()
TTbar_TTDown.SetName("TTbar_TTDown")
T_INFILE_TTDown = inFile.Get("tihTdn")
T_TTDown = T_INFILE_TTDown.Clone()
T_TTDown.SetName("T_TTDown")
Tbar_INFILE_TTDown = inFile.Get("tbihTdn")
Tbar_TTDown = Tbar_INFILE_TTDown.Clone()
Tbar_TTDown.SetName("Tbar_TTDown")
tW_INFILE_TTDown = inFile.Get("t_twihTdn")
tW_TTDown = tW_INFILE_TTDown.Clone()
tW_TTDown.SetName("tW_TTDown")
Drell_INFILE_TTDown = inFile.Get("zihTdn")
Drell_TTDown = Drell_INFILE_TTDown.Clone()
Drell_TTDown.SetName("Drell_TTDown")
VV_INFILE_TTDown = inFile.Get("vvihTdn")
VV_TTDown = VV_INFILE_TTDown.Clone()
VV_TTDown.SetName("VV_TTDown")
#QCD_INFILE_TTDown = inFile.Get("qhTdn")
#QCD_TTDown = QCD_INFILE_TTDown.Clone()
#QCD_TTDown.SetName("QCD_TTDown")

# Muon Up
Wbb_INFILE_muonUp = inFile.Get("wbbihUp")
Wbb_muonUp = Wbb_INFILE_muonUp.Clone()
Wbb_muonUp.SetName("Wbb_muonUp")
Wcc_INFILE_muonUp = inFile.Get("wccihUp")
Wcc_muonUp = Wcc_INFILE_muonUp.Clone()
Wcc_muonUp.SetName("Wcc_muonUp")
TTbar_INFILE_muonUp = inFile.Get("ttbihUp")
TTbar_muonUp = TTbar_INFILE_muonUp.Clone()
TTbar_muonUp.SetName("TTbar_muonUp")
T_INFILE_muonUp = inFile.Get("tihUp")
T_muonUp = T_INFILE_muonUp.Clone()
T_muonUp.SetName("T_muonUp")
Tbar_INFILE_muonUp = inFile.Get("tbihUp")
Tbar_muonUp = Tbar_INFILE_muonUp.Clone()
Tbar_muonUp.SetName("Tbar_muonUp")
tW_INFILE_muonUp = inFile.Get("t_twihUp")
tW_muonUp = tW_INFILE_muonUp.Clone()
tW_muonUp.SetName("tW_muonUp")
Drell_INFILE_muonUp = inFile.Get("zihUp")
Drell_muonUp = Drell_INFILE_muonUp.Clone()
Drell_muonUp.SetName("Drell_muonUp")
VV_INFILE_muonUp = inFile.Get("vvihUp")
VV_muonUp = VV_INFILE_muonUp.Clone()
VV_muonUp.SetName("VV_muonUp")
QCD_INFILE_muonUp = inFile.Get("qhUp")
QCD_muonUp = QCD_INFILE_muonUp.Clone()
QCD_muonUp.SetName("QCD_muonUp")

# Muon Down
Wbb_INFILE_muonDown = inFile.Get("wbbihDn")
Wbb_muonDown = Wbb_INFILE_muonDown.Clone()
Wbb_muonDown.SetName("Wbb_muonDown")
Wcc_INFILE_muonDown = inFile.Get("wccihDn")
Wcc_muonDown = Wcc_INFILE_muonDown.Clone()
Wcc_muonDown.SetName("Wcc_muonDown")
TTbar_INFILE_muonDown = inFile.Get("ttbihDn")
TTbar_muonDown = TTbar_INFILE_muonDown.Clone()
TTbar_muonDown.SetName("TTbar_muonDown")
T_INFILE_muonDown = inFile.Get("tihDn")
T_muonDown = T_INFILE_muonDown.Clone()
T_muonDown.SetName("T_muonDown")
Tbar_INFILE_muonDown = inFile.Get("tbihDn")
Tbar_muonDown = Tbar_INFILE_muonDown.Clone()
Tbar_muonDown.SetName("Tbar_muonDown")
tW_INFILE_muonDown = inFile.Get("t_twihDn")
tW_muonDown = tW_INFILE_muonDown.Clone()
tW_muonDown.SetName("tW_muonDown")
Drell_INFILE_muonDown = inFile.Get("zihDn")
Drell_muonDown = Drell_INFILE_muonDown.Clone()
Drell_muonDown.SetName("Drell_muonDown")
VV_INFILE_muonDown = inFile.Get("vvihDn")
VV_muonDown = VV_INFILE_muonDown.Clone()
VV_muonDown.SetName("VV_muonDown")
QCD_INFILE_muonDown = inFile.Get("qhDn")
QCD_muonDown = QCD_INFILE_muonDown.Clone()
QCD_muonDown.SetName("QCD_muonDown")

# Jet Up
Wbb_INFILE_jetUp = inFile.Get("wbbihJUp")
Wbb_jetUp = Wbb_INFILE_jetUp.Clone()
Wbb_jetUp.SetName("Wbb_jetUp")
Wcc_INFILE_jetUp = inFile.Get("wccihJUp")
Wcc_jetUp = Wcc_INFILE_jetUp.Clone()
Wcc_jetUp.SetName("Wcc_jetUp")
TTbar_INFILE_jetUp = inFile.Get("ttbihJUp")
TTbar_jetUp = TTbar_INFILE_jetUp.Clone()
TTbar_jetUp.SetName("TTbar_jetUp")
T_INFILE_jetUp = inFile.Get("tihJUp")
T_jetUp = T_INFILE_jetUp.Clone()
T_jetUp.SetName("T_jetUp")
Tbar_INFILE_jetUp = inFile.Get("tbihJUp")
Tbar_jetUp = Tbar_INFILE_jetUp.Clone()
Tbar_jetUp.SetName("Tbar_jetUp")
tW_INFILE_jetUp = inFile.Get("t_twihJUp")
tW_jetUp = tW_INFILE_jetUp.Clone()
tW_jetUp.SetName("tW_jetUp")
Drell_INFILE_jetUp = inFile.Get("zihJUp")
Drell_jetUp = Drell_INFILE_jetUp.Clone()
Drell_jetUp.SetName("Drell_jetUp")
VV_INFILE_jetUp = inFile.Get("vvihJUp")
VV_jetUp = VV_INFILE_jetUp.Clone()
VV_jetUp.SetName("VV_jetUp")
QCD_INFILE_jetUp = inFile.Get("qhJUp")
QCD_jetUp = QCD_INFILE_jetUp.Clone()
QCD_jetUp.SetName("QCD_jetUp")

# Jet Down
Wbb_INFILE_jetDown = inFile.Get("wbbihJDn")
Wbb_jetDown = Wbb_INFILE_jetDown.Clone()
Wbb_jetDown.SetName("Wbb_jetDown")
Wcc_INFILE_jetDown = inFile.Get("wccihJDn")
Wcc_jetDown = Wcc_INFILE_jetDown.Clone()
Wcc_jetDown.SetName("Wcc_jetDown")
TTbar_INFILE_jetDown = inFile.Get("ttbihJDn")
TTbar_jetDown = TTbar_INFILE_jetDown.Clone()
TTbar_jetDown.SetName("TTbar_jetDown")
T_INFILE_jetDown = inFile.Get("tihJDn")
T_jetDown = T_INFILE_jetDown.Clone()
T_jetDown.SetName("T_jetDown")
Tbar_INFILE_jetDown = inFile.Get("tbihJDn")
Tbar_jetDown = Tbar_INFILE_jetDown.Clone()
Tbar_jetDown.SetName("Tbar_jetDown")
tW_INFILE_jetDown = inFile.Get("t_twihJDn")
tW_jetDown = tW_INFILE_jetDown.Clone()
tW_jetDown.SetName("tW_jetDown")
Drell_INFILE_jetDown = inFile.Get("zihJDn")
Drell_jetDown = Drell_INFILE_jetDown.Clone()
Drell_jetDown.SetName("Drell_jetDown")
VV_INFILE_jetDown = inFile.Get("vvihJDn")
VV_jetDown = VV_INFILE_jetDown.Clone()
VV_jetDown.SetName("VV_jetDown")
QCD_INFILE_jetDown = inFile.Get("qhJDn")
QCD_jetDown = QCD_INFILE_jetDown.Clone()
QCD_jetDown.SetName("QCD_jetDown")

# UCE Up
Wbb_INFILE_jetUCEUp = inFile.Get("wbbihUUp")
Wbb_jetUCEUp = Wbb_INFILE_jetUCEUp.Clone()
Wbb_jetUCEUp.SetName("Wbb_jetUCEUp")
Wcc_INFILE_jetUCEUp = inFile.Get("wccihUUp")
Wcc_jetUCEUp = Wcc_INFILE_jetUCEUp.Clone()
Wcc_jetUCEUp.SetName("Wcc_jetUCEUp")
TTbar_INFILE_jetUCEUp = inFile.Get("ttbihUUp")
TTbar_jetUCEUp = TTbar_INFILE_jetUCEUp.Clone()
TTbar_jetUCEUp.SetName("TTbar_jetUCEUp")
T_INFILE_jetUCEUp = inFile.Get("tihUUp")
T_jetUCEUp = T_INFILE_jetUCEUp.Clone()
T_jetUCEUp.SetName("T_jetUCEUp")
Tbar_INFILE_jetUCEUp = inFile.Get("tbihUUp")
Tbar_jetUCEUp = Tbar_INFILE_jetUCEUp.Clone()
Tbar_jetUCEUp.SetName("Tbar_jetUCEUp")
tW_INFILE_jetUCEUp = inFile.Get("t_twihUUp")
tW_jetUCEUp = tW_INFILE_jetUCEUp.Clone()
tW_jetUCEUp.SetName("tW_jetUCEUp")
Drell_INFILE_jetUCEUp = inFile.Get("zihUUp")
Drell_jetUCEUp = Drell_INFILE_jetUCEUp.Clone()
Drell_jetUCEUp.SetName("Drell_jetUCEUp")
VV_INFILE_jetUCEUp = inFile.Get("vvihUUp")
VV_jetUCEUp = VV_INFILE_jetUCEUp.Clone()
VV_jetUCEUp.SetName("VV_jetUCEUp")
QCD_INFILE_jetUCEUp = inFile.Get("qhUUp")
QCD_jetUCEUp = QCD_INFILE_jetUCEUp.Clone()
QCD_jetUCEUp.SetName("QCD_jetUCEUp")

# UCE Down
Wbb_INFILE_jetUCEDown = inFile.Get("wbbihUDn")
Wbb_jetUCEDown = Wbb_INFILE_jetUCEDown.Clone()
Wbb_jetUCEDown.SetName("Wbb_jetUCEDown")
Wcc_INFILE_jetUCEDown = inFile.Get("wccihUDn")
Wcc_jetUCEDown = Wcc_INFILE_jetUCEDown.Clone()
Wcc_jetUCEDown.SetName("Wcc_jetUCEDown")
TTbar_INFILE_jetUCEDown = inFile.Get("ttbihUDn")
TTbar_jetUCEDown = TTbar_INFILE_jetUCEDown.Clone()
TTbar_jetUCEDown.SetName("TTbar_jetUCEDown")
T_INFILE_jetUCEDown = inFile.Get("tihUDn")
T_jetUCEDown = T_INFILE_jetUCEDown.Clone()
T_jetUCEDown.SetName("T_jetUCEDown")
Tbar_INFILE_jetUCEDown = inFile.Get("tbihUDn")
Tbar_jetUCEDown = Tbar_INFILE_jetUCEDown.Clone()
Tbar_jetUCEDown.SetName("Tbar_jetUCEDown")
tW_INFILE_jetUCEDown = inFile.Get("t_twihUDn")
tW_jetUCEDown = tW_INFILE_jetUCEDown.Clone()
tW_jetUCEDown.SetName("tW_jetUCEDown")
Drell_INFILE_jetUCEDown = inFile.Get("zihUDn")
Drell_jetUCEDown = Drell_INFILE_jetUCEDown.Clone()
Drell_jetUCEDown.SetName("Drell_jetUCEDown")
VV_INFILE_jetUCEDown = inFile.Get("vvihUDn")
VV_jetUCEDown = VV_INFILE_jetUCEDown.Clone()
VV_jetUCEDown.SetName("VV_jetUCEDown")
QCD_INFILE_jetUCEDown = inFile.Get("qhUDn")
QCD_jetUCEDown = QCD_INFILE_jetUCEDown.Clone()
QCD_jetUCEDown.SetName("QCD_jetUCEDown")

outFile.Write()
