#!/usr/bin/env python
'''
Rename histograms for 8TeV datacards 
Author: T.M.Perry
'''
import ROOT
from ROOT import *
import sys

#inFilename = raw_input ('Name of File to be Renamed (no .root):\n')

rebin = 1

inFilenames=[
sys.argv[1],sys.argv[2],sys.argv[3]
]
Wbb4Fnames=[
sys.argv[4],sys.argv[5],sys.argv[6]
]
#inFilenames = [
#"PS6c_08sptr_Datacard_2j2525_2bt_mt",
#"PS6c_05sptr_Datacard_2j2525_2bt_1m1e_mt",
#"PS6c_08sptr_Datacard_3j2525_2bt_mt",
#]
#Wbb4Fnames = [
#"PS6c_05sptr_Wbb_4F_mt",
#"PS6c_05sptr_TT_1m1e_4F_mt",
#"PS6c_05sptr_TT_3j_4F_mt",
#]

for inFilename,Wbb4Fname in zip(inFilenames,Wbb4Fnames):
 same = False
 if inFilename == Wbb4Fname: same = True
 inFile = TFile(inFilename+'.root')
 w4fFile = TFile(Wbb4Fname+'.root')
 
 outFile=gROOT.FindObject('Renamed4F_'+inFilename+'.root')
 if outFile : outFile.Close()
 outFile = TFile('Renamed4F_'+inFilename+'.root','RECREATE','renamed histograms')
 log = open('Renamed4F_'+inFilename+'.log','a')
 
 # Unshifted
 data_obs_INFILE = inFile.Get("dataih")
 data_obs = data_obs_INFILE.Clone()
 data_obs.SetName("data_obs")
 data_obs.Rebin(rebin)
 
 Wbb_INFILE = inFile.Get("wbbihNo")
 Wbb = Wbb_INFILE.Clone()
 Wbb.SetName("Wbb")
 if same: W4F_INFILE = w4fFile.Get("wbbihNo")
 if not same: W4F_INFILE = w4fFile.Get("W4F_No")
 W4F = W4F_INFILE.Clone()
 W4F.SetName("W4F")
 W4F.Scale(Wbb.Integral(-100,10000)/W4F.Integral(-100,10000))
 TTbar_INFILE = inFile.Get("ttbihNo")
 TTbar = TTbar_INFILE.Clone()
 TTbar.SetName("TTbar")
 Wcc_INFILE = inFile.Get("wccihNo")
 Wcc = Wcc_INFILE.Clone()
 Wcc.SetName("Wcc")
 Wl_INFILE = inFile.Get("wlihNo")
 Wl = Wl_INFILE.Clone()
 Wl.SetName("Wl")
 Wl.Add(inFile.Get("wcihNo"))
 T_INFILE = inFile.Get("tihNo")
 T = T_INFILE.Clone()
 T.SetName("T")
 Tbar_INFILE = inFile.Get("tbihNo")
 Tbar = Tbar_INFILE.Clone()
 Tbar.SetName("Tbar")
 tW_INFILE = inFile.Get("t_twihNo")
 tW = tW_INFILE.Clone()
 tW.SetName("tW")
 Drell_INFILE = inFile.Get("zihNo")
 Drell = Drell_INFILE.Clone()
 Drell.SetName("Drell")
 VV_INFILE = inFile.Get("vvihNo")
 VV = VV_INFILE.Clone()
 VV.SetName("VV")
 QCD_INFILE = inFile.Get("qhNo")
 QCD = QCD_INFILE.Clone()
 QCD.SetName("QCD")
 Wbb.Rebin(rebin)
 W4F.Rebin(rebin)
 TTbar.Rebin(rebin)
 Wcc.Rebin(rebin)
 T.Rebin(rebin)
 Tbar.Rebin(rebin)
 tW.Rebin(rebin)
 Drell.Rebin(rebin)
 VV.Rebin(rebin)
 QCD.Rebin(rebin)
 
 log.write('\n\n')
 log.write("data:  "+str(data_obs.Integral())+'\n')
 log.write("Wbb:   "+str(Wbb.Integral())     +'\n')
 log.write("TTbar: "+str(TTbar.Integral())   +'\n')
 log.write("Wcc:   "+str(Wcc.Integral())     +'\n')
 log.write("Wl:    "+str(Wl.Integral())      +'\n')
 log.write("T:     "+str(T.Integral())       +'\n')
 log.write("Tbar:  "+str(Tbar.Integral())    +'\n')
 log.write("tW:    "+str(tW.Integral())      +'\n')
 log.write("Drell: "+str(Drell.Integral())   +'\n')
 log.write("VV:    "+str(VV.Integral())      +'\n')
 log.write("QCD:   "+str(QCD.Integral())     +'\n')
 log.close()
 
# # TTbar Up
# Wbb_INFILE_TTUp = inFile.Get("wbbihTup")
# Wbb_TTUp = Wbb_INFILE_TTUp.Clone()
# Wbb_TTUp.SetName("Wbb_TTUp")
# W4F_INFILE_TTup = w4fFile.Get("W4F_TTUp")
# W4F_TTup = W4F_INFILE_TTup.Clone()
# W4F_TTup.SetName("W4F_TTup")
# W4F_TTup.Scale(Wbb_TTup.Integral(-100,10000)/W4F_TTup.Integral(-100,10000))
# Wcc_INFILE_TTUp = inFile.Get("wccihTup")
# Wcc_TTUp = Wcc_INFILE_TTUp.Clone()
# Wcc_TTUp.SetName("Wcc_TTUp")
# Wl_INFILE_TTUp = inFile.Get("wlihTup")
# Wl_TTUp = Wl_INFILE_TTUp.Clone()
# Wl_TTUp.SetName("Wl_TTUp")
# Wl_TTUp.Add(inFile.Get("wcihTup"))
# TTbar_INFILE_TTUp = inFile.Get("ttbihTup")
# TTbar_TTUp = TTbar_INFILE_TTUp.Clone()
# TTbar_TTUp.SetName("TTbar_TTUp")
# T_INFILE_TTUp = inFile.Get("tihTup")
# T_TTUp = T_INFILE_TTUp.Clone()
# T_TTUp.SetName("T_TTUp")
# Tbar_INFILE_TTUp = inFile.Get("tbihTup")
# Tbar_TTUp = Tbar_INFILE_TTUp.Clone()
# Tbar_TTUp.SetName("Tbar_TTUp")
# tW_INFILE_TTUp = inFile.Get("t_twihTup")
# tW_TTUp = tW_INFILE_TTUp.Clone()
# tW_TTUp.SetName("tW_TTUp")
# Drell_INFILE_TTUp = inFile.Get("zihTup")
# Drell_TTUp = Drell_INFILE_TTUp.Clone()
# Drell_TTUp.SetName("Drell_TTUp")
# VV_INFILE_TTUp = inFile.Get("vvihTup")
# VV_TTUp = VV_INFILE_TTUp.Clone()
# VV_TTUp.SetName("VV_TTUp")
# QCD_INFILE_TTUp = inFile.Get("qhTup")
# QCD_TTUp = QCD_INFILE_TTUp.Clone()
# QCD_TTUp.SetName("QCD_TTUp")
# Wbb_TTUp.Rebin(rebin)
# W4F_TTUp.Rebin(rebin)
# TTbar_TTUp.Rebin(rebin)
# Wcc_TTUp.Rebin(rebin)
# T_TTUp.Rebin(rebin)
# Tbar_TTUp.Rebin(rebin)
# tW_TTUp.Rebin(rebin)
# Drell_TTUp.Rebin(rebin)
# VV_TTUp.Rebin(rebin)
# QCD_TTUp.Rebin(rebin)
# 
# # TTbar Down
# Wbb_INFILE_TTDown = inFile.Get("wbbihTdn")
# Wbb_TTDown = Wbb_INFILE_TTDown.Clone()
# Wbb_TTDown.SetName("Wbb_TTDown")
# W4F_INFILE_TTDown = w4fFile.Get("W4F_TTDown")
# W4F_TTDown = W4F_INFILE_TTDown.Clone()
# W4F_TTDown.SetName("W4F_TTDown")
# W4F_TTDown.Scale(Wbb_TTDown.Integral(-100,10000)/W4F_TTDown.Integral(-100,10000))
# Wcc_INFILE_TTDown = inFile.Get("wccihTdn")
# Wcc_TTDown = Wcc_INFILE_TTDown.Clone()
# Wcc_TTDown.SetName("Wcc_TTDown")
# Wl_INFILE_TTDown = inFile.Get("wlihTdn")
# Wl_TTDown = Wl_INFILE_TTDown.Clone()
# Wl_TTDown.SetName("Wl_TTDown")
# Wl_TTDown.Add(inFile.Get("wcihTdn"))
# TTbar_INFILE_TTDown = inFile.Get("ttbihTdn")
# TTbar_TTDown = TTbar_INFILE_TTDown.Clone()
# TTbar_TTDown.SetName("TTbar_TTDown")
# T_INFILE_TTDown = inFile.Get("tihTdn")
# T_TTDown = T_INFILE_TTDown.Clone()
# T_TTDown.SetName("T_TTDown")
# Tbar_INFILE_TTDown = inFile.Get("tbihTdn")
# Tbar_TTDown = Tbar_INFILE_TTDown.Clone()
# Tbar_TTDown.SetName("Tbar_TTDown")
# tW_INFILE_TTDown = inFile.Get("t_twihTdn")
# tW_TTDown = tW_INFILE_TTDown.Clone()
# tW_TTDown.SetName("tW_TTDown")
# Drell_INFILE_TTDown = inFile.Get("zihTdn")
# Drell_TTDown = Drell_INFILE_TTDown.Clone()
# Drell_TTDown.SetName("Drell_TTDown")
# VV_INFILE_TTDown = inFile.Get("vvihTdn")
# VV_TTDown = VV_INFILE_TTDown.Clone()
# VV_TTDown.SetName("VV_TTDown")
# QCD_INFILE_TTDown = inFile.Get("qhTdn")
# QCD_TTDown = QCD_INFILE_TTDown.Clone()
# QCD_TTDown.SetName("QCD_TTDown")
# Wbb_TTDown.Rebin(rebin)
# Wbb_TTDown.Rebin(rebin)
# TTbar_TTDown.Rebin(rebin)
# Wcc_TTDown.Rebin(rebin)
# T_TTDown.Rebin(rebin)
# Tbar_TTDown.Rebin(rebin)
# tW_TTDown.Rebin(rebin)
# Drell_TTDown.Rebin(rebin)
# VV_TTDown.Rebin(rebin)
# QCD_TTDown.Rebin(rebin)
 
 # Muon Up
 Wbb_INFILE_muonUp = inFile.Get("wbbihUp")
 Wbb_muonUp = Wbb_INFILE_muonUp.Clone()
 Wbb_muonUp.SetName("Wbb_muonUp")
 if same: W4F_INFILE_muonUp = w4fFile.Get("wbbihUp")
 if not same: W4F_INFILE_muonUp = w4fFile.Get("W4F_muonUp")
 W4F_muonUp = W4F_INFILE_muonUp.Clone()
 W4F_muonUp.SetName("W4F_muonUp")
 W4F_muonUp.Scale(Wbb_muonUp.Integral(-100,10000)/W4F_muonUp.Integral(-100,10000))
 Wcc_INFILE_muonUp = inFile.Get("wccihUp")
 Wcc_muonUp = Wcc_INFILE_muonUp.Clone()
 Wcc_muonUp.SetName("Wcc_muonUp")
 Wl_INFILE_muonUp = inFile.Get("wlihUp")
 Wl_muonUp = Wl_INFILE_muonUp.Clone()
 Wl_muonUp.SetName("Wl_muonUp")
 Wl_muonUp.Add(inFile.Get("wcihUp"))
 TTbar_INFILE_muonUp = inFile.Get("ttbihUp")
 TTbar_muonUp = TTbar_INFILE_muonUp.Clone()
 TTbar_muonUp.SetName("TTbar_muonUp")
 T_INFILE_muonUp = inFile.Get("tihUp")
 T_muonUp = T_INFILE_muonUp.Clone()
 T_muonUp.SetName("T_muonUp")
 Tbar_INFILE_muonUp = inFile.Get("tbihUp")
 Tbar_muonUp = Tbar_INFILE_muonUp.Clone()
 Tbar_muonUp.SetName("Tbar_muonUp")
 tW_INFILE_muonUp = inFile.Get("t_twihUp")
 tW_muonUp = tW_INFILE_muonUp.Clone()
 tW_muonUp.SetName("tW_muonUp")
 Drell_INFILE_muonUp = inFile.Get("zihUp")
 Drell_muonUp = Drell_INFILE_muonUp.Clone()
 Drell_muonUp.SetName("Drell_muonUp")
 VV_INFILE_muonUp = inFile.Get("vvihUp")
 VV_muonUp = VV_INFILE_muonUp.Clone()
 VV_muonUp.SetName("VV_muonUp")
 QCD_INFILE_muonUp = inFile.Get("qhUp")
 QCD_muonUp = QCD_INFILE_muonUp.Clone()
 QCD_muonUp.SetName("QCD_muonUp")
 Wbb_muonUp.Rebin(rebin)
 W4F_muonUp.Rebin(rebin)
 TTbar_muonUp.Rebin(rebin)
 Wcc_muonUp.Rebin(rebin)
 T_muonUp.Rebin(rebin)
 Tbar_muonUp.Rebin(rebin)
 tW_muonUp.Rebin(rebin)
 Drell_muonUp.Rebin(rebin)
 VV_muonUp.Rebin(rebin)
 QCD_muonUp.Rebin(rebin)
 
 # Muon Down
 Wbb_INFILE_muonDown = inFile.Get("wbbihDn")
 Wbb_muonDown = Wbb_INFILE_muonDown.Clone()
 Wbb_muonDown.SetName("Wbb_muonDown")
 if same: W4F_INFILE_muonDown = w4fFile.Get("wbbihDn")
 if not same: W4F_INFILE_muonDown = w4fFile.Get("W4F_muonDown")
 W4F_muonDown = W4F_INFILE_muonDown.Clone()
 W4F_muonDown.SetName("W4F_muonDown")
 W4F_muonDown.Scale(Wbb_muonDown.Integral(-100,10000)/W4F_muonDown.Integral(-100,10000))
 Wcc_INFILE_muonDown = inFile.Get("wccihDn")
 Wcc_muonDown = Wcc_INFILE_muonDown.Clone()
 Wcc_muonDown.SetName("Wcc_muonDown")
 Wl_INFILE_muonDown = inFile.Get("wlihUp")
 Wl_muonDown = Wl_INFILE_muonDown.Clone()
 Wl_muonDown.SetName("Wl_muonDown")
 Wl_muonDown.Add(inFile.Get("wcihUp"))
 TTbar_INFILE_muonDown = inFile.Get("ttbihDn")
 TTbar_muonDown = TTbar_INFILE_muonDown.Clone()
 TTbar_muonDown.SetName("TTbar_muonDown")
 T_INFILE_muonDown = inFile.Get("tihDn")
 T_muonDown = T_INFILE_muonDown.Clone()
 T_muonDown.SetName("T_muonDown")
 Tbar_INFILE_muonDown = inFile.Get("tbihDn")
 Tbar_muonDown = Tbar_INFILE_muonDown.Clone()
 Tbar_muonDown.SetName("Tbar_muonDown")
 tW_INFILE_muonDown = inFile.Get("t_twihDn")
 tW_muonDown = tW_INFILE_muonDown.Clone()
 tW_muonDown.SetName("tW_muonDown")
 Drell_INFILE_muonDown = inFile.Get("zihDn")
 Drell_muonDown = Drell_INFILE_muonDown.Clone()
 Drell_muonDown.SetName("Drell_muonDown")
 VV_INFILE_muonDown = inFile.Get("vvihDn")
 VV_muonDown = VV_INFILE_muonDown.Clone()
 VV_muonDown.SetName("VV_muonDown")
 QCD_INFILE_muonDown = inFile.Get("qhDn")
 QCD_muonDown = QCD_INFILE_muonDown.Clone()
 QCD_muonDown.SetName("QCD_muonDown")
 Wbb_muonDown.Rebin(rebin)
 W4F_muonDown.Rebin(rebin)
 TTbar_muonDown.Rebin(rebin)
 Wcc_muonDown.Rebin(rebin)
 T_muonDown.Rebin(rebin)
 Tbar_muonDown.Rebin(rebin)
 tW_muonDown.Rebin(rebin)
 Drell_muonDown.Rebin(rebin)
 VV_muonDown.Rebin(rebin)
 QCD_muonDown.Rebin(rebin)
 
 # Jet Up
 Wbb_INFILE_jetUp = inFile.Get("wbbihJUp")
 Wbb_jetUp = Wbb_INFILE_jetUp.Clone()
 Wbb_jetUp.SetName("Wbb_jetUp")
 if same: W4F_INFILE_jetUp = w4fFile.Get("wbbihJUp")
 if not same: W4F_INFILE_jetUp = w4fFile.Get("W4F_jetUp")
 W4F_jetUp = W4F_INFILE_jetUp.Clone()
 W4F_jetUp.SetName("W4F_jetUp")
 W4F_jetUp.Scale(Wbb_jetUp.Integral(-100,10000)/W4F_jetUp.Integral(-100,10000))
 Wcc_INFILE_jetUp = inFile.Get("wccihJUp")
 Wcc_jetUp = Wcc_INFILE_jetUp.Clone()
 Wcc_jetUp.SetName("Wcc_jetUp")
 Wl_INFILE_jetUp = inFile.Get("wlihJUp")
 Wl_jetUp = Wl_INFILE_jetUp.Clone()
 Wl_jetUp.SetName("Wl_jetUp")
 Wl_jetUp.Add(inFile.Get("wcihJUp"))
 TTbar_INFILE_jetUp = inFile.Get("ttbihJUp")
 TTbar_jetUp = TTbar_INFILE_jetUp.Clone()
 TTbar_jetUp.SetName("TTbar_jetUp")
 T_INFILE_jetUp = inFile.Get("tihJUp")
 T_jetUp = T_INFILE_jetUp.Clone()
 T_jetUp.SetName("T_jetUp")
 Tbar_INFILE_jetUp = inFile.Get("tbihJUp")
 Tbar_jetUp = Tbar_INFILE_jetUp.Clone()
 Tbar_jetUp.SetName("Tbar_jetUp")
 tW_INFILE_jetUp = inFile.Get("t_twihJUp")
 tW_jetUp = tW_INFILE_jetUp.Clone()
 tW_jetUp.SetName("tW_jetUp")
 Drell_INFILE_jetUp = inFile.Get("zihJUp")
 Drell_jetUp = Drell_INFILE_jetUp.Clone()
 Drell_jetUp.SetName("Drell_jetUp")
 VV_INFILE_jetUp = inFile.Get("vvihJUp")
 VV_jetUp = VV_INFILE_jetUp.Clone()
 VV_jetUp.SetName("VV_jetUp")
 QCD_INFILE_jetUp = inFile.Get("qhJUp")
 QCD_jetUp = QCD_INFILE_jetUp.Clone()
 QCD_jetUp.SetName("QCD_jetUp")
 Wbb_jetUp.Rebin(rebin)
 W4F_jetUp.Rebin(rebin)
 TTbar_jetUp.Rebin(rebin)
 Wcc_jetUp.Rebin(rebin)
 T_jetUp.Rebin(rebin)
 Tbar_jetUp.Rebin(rebin)
 tW_jetUp.Rebin(rebin)
 Drell_jetUp.Rebin(rebin)
 VV_jetUp.Rebin(rebin)
 QCD_jetUp.Rebin(rebin)
 
 # Jet Down
 Wbb_INFILE_jetDown = inFile.Get("wbbihJDn")
 Wbb_jetDown = Wbb_INFILE_jetDown.Clone()
 Wbb_jetDown.SetName("Wbb_jetDown")
 if same: W4F_INFILE_jetDown = w4fFile.Get("wbbihJDn")
 if not same: W4F_INFILE_jetDown = w4fFile.Get("W4F_jetDown")
 W4F_jetDown = W4F_INFILE_jetDown.Clone()
 W4F_jetDown.SetName("W4F_jetDown")
 W4F_jetDown.Scale(Wbb_jetDown.Integral(-100,10000)/W4F_jetDown.Integral(-100,10000))
 Wcc_INFILE_jetDown = inFile.Get("wccihJDn")
 Wcc_jetDown = Wcc_INFILE_jetDown.Clone()
 Wcc_jetDown.SetName("Wcc_jetDown")
 Wl_INFILE_jetDown = inFile.Get("wlihJDn")
 Wl_jetDown = Wl_INFILE_jetDown.Clone()
 Wl_jetDown.SetName("Wl_jetDown")
 Wl_jetDown.Add(inFile.Get("wcihJDn"))
 TTbar_INFILE_jetDown = inFile.Get("ttbihJDn")
 TTbar_jetDown = TTbar_INFILE_jetDown.Clone()
 TTbar_jetDown.SetName("TTbar_jetDown")
 T_INFILE_jetDown = inFile.Get("tihJDn")
 T_jetDown = T_INFILE_jetDown.Clone()
 T_jetDown.SetName("T_jetDown")
 Tbar_INFILE_jetDown = inFile.Get("tbihJDn")
 Tbar_jetDown = Tbar_INFILE_jetDown.Clone()
 Tbar_jetDown.SetName("Tbar_jetDown")
 tW_INFILE_jetDown = inFile.Get("t_twihJDn")
 tW_jetDown = tW_INFILE_jetDown.Clone()
 tW_jetDown.SetName("tW_jetDown")
 Drell_INFILE_jetDown = inFile.Get("zihJDn")
 Drell_jetDown = Drell_INFILE_jetDown.Clone()
 Drell_jetDown.SetName("Drell_jetDown")
 VV_INFILE_jetDown = inFile.Get("vvihJDn")
 VV_jetDown = VV_INFILE_jetDown.Clone()
 VV_jetDown.SetName("VV_jetDown")
 QCD_INFILE_jetDown = inFile.Get("qhJDn")
 QCD_jetDown = QCD_INFILE_jetDown.Clone()
 QCD_jetDown.SetName("QCD_jetDown")
 Wbb_jetDown.Rebin(rebin)
 W4F_jetDown.Rebin(rebin)
 TTbar_jetDown.Rebin(rebin)
 Wcc_jetDown.Rebin(rebin)
 T_jetDown.Rebin(rebin)
 Tbar_jetDown.Rebin(rebin)
 tW_jetDown.Rebin(rebin)
 Drell_jetDown.Rebin(rebin)
 VV_jetDown.Rebin(rebin)
 QCD_jetDown.Rebin(rebin)
 
 # UCE Up
 Wbb_INFILE_UCEUp = inFile.Get("wbbihUUp")
 Wbb_UCEUp = Wbb_INFILE_UCEUp.Clone()
 Wbb_UCEUp.SetName("Wbb_UCEUp")
 if same: W4F_INFILE_UCEUp = w4fFile.Get("wbbihUUp")
 if not same: W4F_INFILE_UCEUp = w4fFile.Get("W4F_UCEUp")
 W4F_UCEUp = W4F_INFILE_UCEUp.Clone()
 W4F_UCEUp.SetName("W4F_UCEUp")
 W4F_UCEUp.Scale(Wbb_UCEUp.Integral(-100,10000)/W4F_UCEUp.Integral(-100,10000))
 Wcc_INFILE_UCEUp = inFile.Get("wccihUUp")
 Wcc_UCEUp = Wcc_INFILE_UCEUp.Clone()
 Wcc_UCEUp.SetName("Wcc_UCEUp")
 Wl_INFILE_UCEUp = inFile.Get("wlihUUp")
 Wl_UCEUp = Wl_INFILE_UCEUp.Clone()
 Wl_UCEUp.SetName("Wl_UCEUp")
 Wl_UCEUp.Add(inFile.Get("wcihUUp"))
 TTbar_INFILE_UCEUp = inFile.Get("ttbihUUp")
 TTbar_UCEUp = TTbar_INFILE_UCEUp.Clone()
 TTbar_UCEUp.SetName("TTbar_UCEUp")
 T_INFILE_UCEUp = inFile.Get("tihUUp")
 T_UCEUp = T_INFILE_UCEUp.Clone()
 T_UCEUp.SetName("T_UCEUp")
 Tbar_INFILE_UCEUp = inFile.Get("tbihUUp")
 Tbar_UCEUp = Tbar_INFILE_UCEUp.Clone()
 Tbar_UCEUp.SetName("Tbar_UCEUp")
 tW_INFILE_UCEUp = inFile.Get("t_twihUUp")
 tW_UCEUp = tW_INFILE_UCEUp.Clone()
 tW_UCEUp.SetName("tW_UCEUp")
 Drell_INFILE_UCEUp = inFile.Get("zihUUp")
 Drell_UCEUp = Drell_INFILE_UCEUp.Clone()
 Drell_UCEUp.SetName("Drell_UCEUp")
 VV_INFILE_UCEUp = inFile.Get("vvihUUp")
 VV_UCEUp = VV_INFILE_UCEUp.Clone()
 VV_UCEUp.SetName("VV_UCEUp")
 QCD_INFILE_UCEUp = inFile.Get("qhUUp")
 QCD_UCEUp = QCD_INFILE_UCEUp.Clone()
 QCD_UCEUp.SetName("QCD_UCEUp")
 Wbb_UCEUp.Rebin(rebin)
 W4F_UCEUp.Rebin(rebin)
 TTbar_UCEUp.Rebin(rebin)
 Wcc_UCEUp.Rebin(rebin)
 T_UCEUp.Rebin(rebin)
 Tbar_UCEUp.Rebin(rebin)
 tW_UCEUp.Rebin(rebin)
 Drell_UCEUp.Rebin(rebin)
 VV_UCEUp.Rebin(rebin)
 QCD_UCEUp.Rebin(rebin)
 
 # UCE Down
 Wbb_INFILE_UCEDown = inFile.Get("wbbihUDn")
 Wbb_UCEDown = Wbb_INFILE_UCEDown.Clone()
 Wbb_UCEDown.SetName("Wbb_UCEDown")
 if same: W4F_INFILE_UCEDown = w4fFile.Get("wbbihUDn")
 if not same: W4F_INFILE_UCEDown = w4fFile.Get("W4F_UCEDown")
 W4F_UCEDown = W4F_INFILE_UCEDown.Clone()
 W4F_UCEDown.SetName("W4F_UCEDown")
 W4F_UCEDown.Scale(Wbb_UCEDown.Integral(-100,10000)/W4F_UCEDown.Integral(-100,10000))
 Wcc_INFILE_UCEDown = inFile.Get("wccihUDn")
 Wcc_UCEDown = Wcc_INFILE_UCEDown.Clone()
 Wcc_UCEDown.SetName("Wcc_UCEDown")
 Wl_INFILE_UCEDown = inFile.Get("wlihUDn")
 Wl_UCEDown = Wl_INFILE_UCEDown.Clone()
 Wl_UCEDown.SetName("Wl_UCEDown")
 Wl_UCEDown.Add(inFile.Get("wcihUDn"))
 TTbar_INFILE_UCEDown = inFile.Get("ttbihUDn")
 TTbar_UCEDown = TTbar_INFILE_UCEDown.Clone()
 TTbar_UCEDown.SetName("TTbar_UCEDown")
 T_INFILE_UCEDown = inFile.Get("tihUDn")
 T_UCEDown = T_INFILE_UCEDown.Clone()
 T_UCEDown.SetName("T_UCEDown")
 Tbar_INFILE_UCEDown = inFile.Get("tbihUDn")
 Tbar_UCEDown = Tbar_INFILE_UCEDown.Clone()
 Tbar_UCEDown.SetName("Tbar_UCEDown")
 tW_INFILE_UCEDown = inFile.Get("t_twihUDn")
 tW_UCEDown = tW_INFILE_UCEDown.Clone()
 tW_UCEDown.SetName("tW_UCEDown")
 Drell_INFILE_UCEDown = inFile.Get("zihUDn")
 Drell_UCEDown = Drell_INFILE_UCEDown.Clone()
 Drell_UCEDown.SetName("Drell_UCEDown")
 VV_INFILE_UCEDown = inFile.Get("vvihUDn")
 VV_UCEDown = VV_INFILE_UCEDown.Clone()
 VV_UCEDown.SetName("VV_UCEDown")
 QCD_INFILE_UCEDown = inFile.Get("qhUDn")
 QCD_UCEDown = QCD_INFILE_UCEDown.Clone()
 QCD_UCEDown.SetName("QCD_UCEDown")
 Wbb_UCEDown.Rebin(rebin)
 W4F_UCEDown.Rebin(rebin)
 TTbar_UCEDown.Rebin(rebin)
 Wcc_UCEDown.Rebin(rebin)
 T_UCEDown.Rebin(rebin)
 Tbar_UCEDown.Rebin(rebin)
 tW_UCEDown.Rebin(rebin)
 Drell_UCEDown.Rebin(rebin)
 VV_UCEDown.Rebin(rebin)
 QCD_UCEDown.Rebin(rebin)
 
 outFile.Write()
